# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Raw/reset_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from typing import Tuple, Any

from PyQt5 import QtCore, QtGui, QtWidgets
from Libs.globals import settings

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(811, 334)
        Dialog.setMinimumSize(QtCore.QSize(811, 334))
        Dialog.setMaximumSize(QtCore.QSize(811, 334))
        Dialog.setStyleSheet("\n"
"QWidget{\n"
"    background-color: black;\n"
"    color: white;\n"
"    font: 10pt \"Serif\";\n"
"}\n"
"#Dialog{\n"
"    border: 1px solid white;\n"
"    border-radius: 5px 10px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setStyleSheet("padding-top: 15px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_password = QtWidgets.QLabel(self.frame_2)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_status = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("color: rgb(185, 185, 185);")
        self.label_status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout.addWidget(self.label_status)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_dismiss = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_dismiss.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_dismiss.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_dismiss.setStyleSheet("QPushButton{\n"
"    border: 1px solid red;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgba(255, 0, 0, 170);\n"
"    color: rgb(208, 208, 208);\n"
"    border: 1px solid rgb(0, 121, 182);\n"
"}\n"
"QPushButton::pressed{\n"
"    margin-top: 2px;\n"
"    margin-bottom: 2px;\n"
"}")
        self.pushButton_dismiss.setObjectName("pushButton_dismiss")
        self.horizontalLayout.addWidget(self.pushButton_dismiss)
        self.pushButton_confirm = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_confirm.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_confirm.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_confirm.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(99, 99, 99);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 153, 229);\n"
"    color: rgb(208, 208, 208);\n"
"    border: 1px solid rgb(0, 121, 182);\n"
"}\n"
"QPushButton::pressed{\n"
"    margin-top: 2px;\n"
"    margin-bottom: 2px;\n"
"}")
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.horizontalLayout.addWidget(self.pushButton_confirm)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 2)
        self.lineEdit_new_password = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_new_password.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    padding-left: 2px;\n"
"    border-color: grey;\n"
"}")
        self.lineEdit_new_password.setObjectName("lineEdit_new_password")
        self.gridLayout.addWidget(self.lineEdit_new_password, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_confirm_password = QtWidgets.QLabel(self.frame)
        self.label_confirm_password.setObjectName("label_confirm_password")
        self.gridLayout_2.addWidget(self.label_confirm_password, 0, 0, 1, 1)
        self.lineEdit_new_password_confirm = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_new_password_confirm.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    padding-left: 2px;\n"
"    border-color: grey;\n"
"}")
        self.lineEdit_new_password_confirm.setObjectName("lineEdit_new_password_confirm")
        self.gridLayout_2.addWidget(self.lineEdit_new_password_confirm, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_password.setText(_translate("Dialog", "Enter new password"))
        self.label_status.setText(_translate("Dialog", "* Password should have minimum 8 characters"))
        self.pushButton_dismiss.setText(_translate("Dialog", "Cancel Reset Password"))
        self.pushButton_confirm.setText(_translate("Dialog", "Confirm"))
        self.label_confirm_password.setText(_translate("Dialog", "Re-enter new password"))


class ResetPassword(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super(ResetPassword, self).__init__(parent=parent)
        self.password_matched = False
        self._password_text = None

        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

        self.setWindowTitle(f"Reset Password {settings.APP_NAME} {settings.App_VERSION} {settings.EXTENSION}")

        self.ui.lineEdit_new_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.ui.lineEdit_new_password_confirm.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)

        self.ui.pushButton_dismiss.clicked.connect(self.dismiss_process)
        self.ui.pushButton_confirm.clicked.connect(self.check_password)

    def dismiss_process(self):
        self.reject()

    def reset_status_label(self):
        self.ui.label_status.setStyleSheet("color: rgb(185, 185, 185);")
        self.ui.label_status.setText("* Password should have minimum 8 characters")

    def check_password(self):
        password_1 = self.ui.lineEdit_new_password.text()
        password_2 = self.ui.lineEdit_new_password_confirm.text()
        if len(password_1) >= 8 and password_1 == password_2:
            self.password_matched = True
            self._password_text = password_2
            self.accept()
        else:
            self._password_text = None
            self.password_matched = False
            self.ui.label_status.setStyleSheet("color: red;")
            if any((len(x) <= 8 for x in (password_1, password_2))):
                self.ui.label_status.setText("Password too short, minimum 8 characters required.")
            else:
                self.ui.label_status.setText("Passwords didn't match. Please try again...")

    def exec_(self) -> Tuple[bool, Any]:
        super(ResetPassword, self).exec_()
        return self.password_matched, self._password_text
