# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Raw/discliamer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(905, 608)
        Dialog.setStyleSheet("#Dialog{\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.0736842 rgba(93, 93, 93, 255), stop:0.342105 rgba(5, 5, 5, 255), stop:0.526316 rgba(0, 0, 0, 255), stop:0.747368 rgba(0, 0, 0, 255), stop:0.915789 rgba(78, 78, 78, 255));\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_heading = QtWidgets.QFrame(self.frame)
        self.frame_heading.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_heading.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_heading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_heading.setObjectName("frame_heading")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_heading)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_heading = QtWidgets.QLabel(self.frame_heading)
        self.label_heading.setStyleSheet("QLabel{\n"
"    color: red;\n"
"    font: 75 20pt \"Serif\";\n"
"}")
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.gridLayout_2.addWidget(self.label_heading, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_heading)
        self.frame_body_holder = QtWidgets.QFrame(self.frame)
        self.frame_body_holder.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_body_holder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body_holder.setObjectName("frame_body_holder")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_body_holder)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_body_holder)
        self.scrollArea.setStyleSheet("#scrollAreaWidgetContents{\n"
"    background-color: transparent;\n"
"}\n"
"#scrollArea{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}\n"
"/* ----------------- scrollbar stylesheet ---------------- */\n"
"QScrollBar:vertical {\n"
"    border: 1px solid transparent;\n"
"    background: transparent;\n"
"    width:15px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #7676F8;\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    background: #7676F8;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #7676F8;\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: 1px solid transparent;\n"
"    background: transparent;\n"
"    height: 15px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #7676F8;\n"
"    min-width: 5px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    /*border: 2px solid grey;*/\n"
"    background: #7676F8;\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: #7676F8;\n"
"    width: 0px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 851, 497))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_disclaimer_body = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_disclaimer_body.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_disclaimer_body.setWordWrap(True)
        self.label_disclaimer_body.setObjectName("label_disclaimer_body")
        self.verticalLayout_3.addWidget(self.label_disclaimer_body)
        self.frame_confirm = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_confirm.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}\n"
"QCheckBox {\n"
"   border: none;\n"
"   color: white;\n"
"}\n"
"QCheckBox::indicator:unchecked{\n"
"    border: 2px solid white;\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 2px solid white;\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    image: url(:/icons/check_icon.png);\n"
"}")
        self.frame_confirm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_confirm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_confirm.setObjectName("frame_confirm")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_confirm)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame_confirm)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_no_show_disclaimer = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_no_show_disclaimer.setObjectName("checkBox_no_show_disclaimer")
        self.verticalLayout_4.addWidget(self.checkBox_no_show_disclaimer)
        self.pushButton_confirm_discliamer = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_confirm_discliamer.setMinimumSize(QtCore.QSize(50, 35))
        self.pushButton_confirm_discliamer.setMaximumSize(QtCore.QSize(160, 50))
        self.pushButton_confirm_discliamer.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 150, 225);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 2px;\n"
"    margin-top: 5px;\n"
"    margin-bottom: -5px;\n"
"}")
        self.pushButton_confirm_discliamer.setObjectName("pushButton_confirm_discliamer")
        self.verticalLayout_4.addWidget(self.pushButton_confirm_discliamer)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.frame_confirm)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.frame_body_holder)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_heading.setText(_translate("Dialog", "Disclaimer"))
        self.label_disclaimer_body.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:12pt;\">The data information was acquired from and is dependent on sources, Algo beacon consider to be credible and cannot guarantee its correctness, and it may be incomplete or condensed data as per the logics we are using. All logics and estimations are based on our best efforts and knowledge as of the report’s publications date and our subject to change at without notice.</span><span style=\" font-size:11pt;\"><br/></span></p><p align=\"center\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\">This website content is for informational purposes only and none of the stock information, Trading in stocks, options and other securities involves risk. The risk of loss in trading securities can be substantial. The risk involved with trading stock; options may not be satisfactory for all investors.</span></p><p align=\"center\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:11pt;\">The information presented in the educational material is not intended for any investment decisions, nor should be construed as advice designed to meet the investment needs of any particular investor. it is very important to do your own analysis before making any investment based on your own personal circumstances.</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:12pt; font-weight:600;\">Note</span></p><p align=\"center\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:14pt;\">We are not a SEBI Registered Advisor; therefore, we accept no responsibility for any trading gains or losses, Please seek advice from your financial advisor.</span></p></body></html>"))
        self.checkBox_no_show_disclaimer.setText(_translate("Dialog", "don\'t show this again"))
        self.pushButton_confirm_discliamer.setText(_translate("Dialog", "I understand"))
from . import icons_rc
