# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Raw/strategy_builder_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(675, 407)
        Dialog.setStyleSheet("QDialog{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_outer = QtWidgets.QFrame(Dialog)
        self.frame_outer.setStyleSheet("#frame_outer{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: white;\n"
"}\n"
"QLabel{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(236, 236, 236);\n"
"}\n"
"QScrollArea {\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: white;\n"
"}\n"
"#scrollAreaWidgetContents{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"}\n"
"QSpinBox, QTimeEdit{\n"
"    padding: 3px; /* make room for the arrows */\n"
"    border: 2px solid rgb(172, 172, 172);\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"    color: rgb(236, 236, 236);\n"
"    selection-color: rgb(43, 43, 43);\n"
"    selection-background-color: rgb(255, 255, 255);\n"
"}\n"
"QSpinBox::up-button, QTimeEdit::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    width: 16px;\n"
"    border-image: url(:/icons/up-arrow.png) 1;\n"
"    border-width: 1px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover, QTimeEdit::up-button:hover {\n"
"    border-image: url(:/icons/up-arrow-hover.png) 1;\n"
"}\n"
"QSpinBox::down-button:hover, QTimeEdit::down-button:hover {\n"
"    border-image: url(:/icons/down-arrow-hover.png) 1;\n"
"}\n"
"\n"
"QSpinBox::down-button, QTimeEdit::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    width: 16px;\n"
"    border-image: url(:/icons/down-arrow.png) 1;\n"
"    border-width: 1px;\n"
"}")
        self.frame_outer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_outer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_outer.setObjectName("frame_outer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_outer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame_outer)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 9)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_strategy_title = QtWidgets.QLabel(self.frame_2)
        self.label_strategy_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_strategy_title.setObjectName("label_strategy_title")
        self.verticalLayout_2.addWidget(self.label_strategy_title)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_outer)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_end_time = QtWidgets.QLabel(self.frame_4)
        self.label_end_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_end_time.setObjectName("label_end_time")
        self.horizontalLayout.addWidget(self.label_end_time)
        self.timeEdit_end_time = QtWidgets.QTimeEdit(self.frame_4)
        self.timeEdit_end_time.setWrapping(False)
        self.timeEdit_end_time.setFrame(True)
        self.timeEdit_end_time.setProperty("showGroupSeparator", False)
        self.timeEdit_end_time.setMaximumTime(QtCore.QTime(15, 30, 0))
        self.timeEdit_end_time.setMinimumTime(QtCore.QTime(9, 16, 0))
        self.timeEdit_end_time.setTime(QtCore.QTime(15, 30, 0))
        self.timeEdit_end_time.setObjectName("timeEdit_end_time")
        self.horizontalLayout.addWidget(self.timeEdit_end_time)
        self.gridLayout_2.addWidget(self.frame_4, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_start_time = QtWidgets.QLabel(self.frame_5)
        self.label_start_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_start_time.setObjectName("label_start_time")
        self.horizontalLayout_2.addWidget(self.label_start_time)
        self.timeEdit_start_time = QtWidgets.QTimeEdit(self.frame_5)
        self.timeEdit_start_time.setWrapping(False)
        self.timeEdit_start_time.setFrame(True)
        self.timeEdit_start_time.setProperty("showGroupSeparator", False)
        self.timeEdit_start_time.setMaximumTime(QtCore.QTime(15, 29, 0))
        self.timeEdit_start_time.setMinimumTime(QtCore.QTime(9, 15, 0))
        self.timeEdit_start_time.setTime(QtCore.QTime(9, 15, 0))
        self.timeEdit_start_time.setObjectName("timeEdit_start_time")
        self.horizontalLayout_2.addWidget(self.timeEdit_start_time)
        self.gridLayout_2.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_frequency = QtWidgets.QLabel(self.frame_7)
        self.label_frequency.setObjectName("label_frequency")
        self.gridLayout_4.addWidget(self.label_frequency, 0, 0, 1, 1)
        self.spinBox_freq = QtWidgets.QSpinBox(self.frame_7)
        self.spinBox_freq.setObjectName("spinBox_freq")
        self.gridLayout_4.addWidget(self.spinBox_freq, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_7, 0, 2, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_6)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 615, 212))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_6, 1, 0, 1, 3)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame_outer, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("#pushButton_close{\n"
"    font: 63 13pt \"Rasa SemiBold\";\n"
"    color: rgb(217, 217, 217);\n"
"    background-color: rgb(180, 0, 0);\n"
"}\n"
"#pushButton_close::hover{\n"
"    background-color: rgb(195, 0, 0);\n"
"}\n"
"#pushButton_confirm{\n"
"    font: 63 13pt \"Rasa SemiBold\";\n"
"    color: rgb(217, 217, 217);\n"
"    background-color: rgb(0, 71, 214);\n"
"}\n"
"#pushButton_confirm::hover{\n"
"    background-color: rgb(0, 57, 171);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(6)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_confirm = QtWidgets.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/check-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_confirm.setIcon(icon)
        self.pushButton_confirm.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.gridLayout_5.addWidget(self.pushButton_confirm, 0, 2, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/close-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon1)
        self.pushButton_close.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_5.addWidget(self.pushButton_close, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.timeEdit_start_time, self.timeEdit_end_time)
        Dialog.setTabOrder(self.timeEdit_end_time, self.spinBox_freq)
        Dialog.setTabOrder(self.spinBox_freq, self.scrollArea)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_strategy_title.setText(_translate("Dialog", "<h2>{Title}</h2>"))
        self.label_end_time.setText(_translate("Dialog", "End Time"))
        self.timeEdit_end_time.setDisplayFormat(_translate("Dialog", "HH:mm"))
        self.label_start_time.setText(_translate("Dialog", "Start Time"))
        self.timeEdit_start_time.setDisplayFormat(_translate("Dialog", "HH:mm"))
        self.label_frequency.setText(_translate("Dialog", "Frequency"))
        self.pushButton_confirm.setText(_translate("Dialog", "Confirm"))
        self.pushButton_close.setText(_translate("Dialog", "Close"))
from . import icons_rc
